# Generated by Django 5.0.14 on 2026-06-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('SHORTLISTED', 'Shortlisted'), ('REJECTED', 'Rejected'), ('OFFERED', 'Offered')], default='APPLIED', max_length=20)),
                ('current_stage', models.CharField(choices=[('APPLIED', 'Applied'), ('APTITUDE', 'Aptitude Test'), ('TECHNICAL', 'Technical Interview'), ('HR', 'HR Interview'), ('OFFERED', 'Offered'), ('REJECTED', 'Rejected')], default='APPLIED', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_name', models.CharField(choices=[('APTITUDE', 'Aptitude Test'), ('TECHNICAL', 'Technical Interview'), ('HR', 'HR Interview'), ('OTHER', 'Other Round')], default='APTITUDE', max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('location', models.CharField(help_text='Venue name or Video Call link', max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('RESCHEDULED', 'Rescheduled'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlacementDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('salary_package', models.DecimalField(decimal_places=2, help_text='Salary package in LPA (Lakhs Per Annum), e.g. 12.50', max_digits=5)),
                ('eligibility_min_cgpa', models.DecimalField(decimal_places=2, default=6.0, help_text='Minimum CGPA required', max_digits=4)),
                ('eligibility_max_backlogs', models.PositiveSmallIntegerField(default=0, help_text='Maximum active backlogs allowed')),
                ('eligible_branches', models.TextField(help_text='Comma-separated eligible branches (e.g. CSE, ECE, IT)')),
                ('required_skills', models.TextField(blank=True, help_text='Comma-separated required skills (e.g. Python, SQL)')),
                ('drive_date', models.DateField()),
                ('registration_deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
