# Generated by Django 5.0.14 on 2026-06-29 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('placements', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='students.studentprofile'),
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='placements.application'),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drives', to='companies.companyprofile'),
        ),
        migrations.AddField(
            model_name='application',
            name='drive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='placements.placementdrive'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('drive', 'student')},
        ),
    ]
